### ISSUE TITLE
Reloaded fails to load because of an error caused by the unhardcoded toolkit

### ISSUE THREAD

**Issue by GODSWOMB** [Secre-C/P5R-Unhardcoded-Toolkit#2]
### This is the error Reloaded outputs:

[Reloaded] Failed to Load Reloaded-II.
Could not find address for LoadDDS
at Unhardcoded_P5R.Utils.<>c__DisplayClass25_0.<SigScan>b__0(PatternScanResult result) in D:\Github\P5R-Unhardcoded-Toolkit\Utils.cs:line 55
at Reloaded.Memory.SigScan.ReloadedII.StartupScanner.RunMainModuleScans()
at Reloaded.Memory.SigScan.ReloadedII.StartupScanner.OnLoaderInitialized()
at Reloaded.Mod.Loader.Loader.LoadForAppConfig(IApplicationConfig applicationConfig)
at Reloaded.Mod.Loader.EntryPoint.LoadMods(IReloadedHooks hooks)
at Reloaded.Mod.Loader.EntryPoint.<>c__DisplayClass14_0.<SetupLoader2>b__1()
at Reloaded.Mod.Loader.EntryPoint.ExecuteTimed(String text, Action action)
at Reloaded.Mod.Loader.EntryPoint.SetupLoader2(EntryPointParameters* parameters)
at Reloaded.Mod.Loader.EntryPoint.SetupLoader(EntryPointParameters* parameters)`

**Comment by Secre-C** [comment]
this should have been fixed in the latest update. try deleting your copy of unhardcoded toolkit and run the game again

**Comment by GODSWOMB** [comment]
Still happening after multiple reinstalls. (Installing through reload, extracting the files manually, letting reload auto download the dependency, which actually throws up another error*) 

I am using version 2.0.0, which is the latest release.

*![stuck](https://github.com/user-attachments/assets/cd9ca601-b45f-43bc-8a3b-b8b28c08636e)

**Comment by Secre-C** [comment]
are you using the latest version of the game?

**Comment by GODSWOMB** [comment]
I'm using an old executable for compatibility with older mods that might've broke with the latest patch of P5. Would an older release of this mod work for older versions of P5? I'm also using this mod in conjunction with your colored chat messages mod.

**Comment by Secre-C** [comment]
the recent update makes the mod compatible with the newest version of p5r, which in turn breaks compatibility with older versions, and is also a massive overhaul of the mod. older versions will work with older executables, but you'd also be missing the new features

**Comment by GODSWOMB** [comment]
So downgrading the unhardcoded toolkit does let Reloaded load properly, but the game crashes not too long after. I'm assuming that the newest version of colored chat only works with the rewritten version of the toolkit. Do you happen to have an older version of the mod I could download?
